<?php

namespace App\Filament;

use Filament\Support\Facades\FilamentIcon;

final class RadaFilamentIcons
{
    public static function register(): void
    {
        FilamentIcon::register([
            'actions::action-group' => 'fas-ellipsis',
            'actions::create-action.grouped' => 'fas-circle-plus',
            'actions::delete-action' => 'fas-trash',
            'actions::delete-action.grouped' => 'fas-trash',
            'actions::delete-action.modal' => 'fas-trash',
            'actions::detach-action' => 'fas-link-slash',
            'actions::detach-action.modal' => 'fas-link-slash',
            'actions::dissociate-action' => 'fas-link-slash',
            'actions::dissociate-action.modal' => 'fas-link-slash',
            'actions::edit-action' => 'fas-pen-to-square',
            'actions::edit-action.grouped' => 'fas-pen-to-square',
            'actions::export-action.grouped' => 'fas-file-export',
            'actions::force-delete-action' => 'fas-trash-can',
            'actions::force-delete-action.grouped' => 'fas-trash-can',
            'actions::force-delete-action.modal' => 'fas-trash-can',
            'actions::import-action.grouped' => 'fas-file-import',
            'actions::modal.confirmation' => 'fas-circle-question',
            'actions::replicate-action' => 'fas-clone',
            'actions::replicate-action.grouped' => 'fas-clone',
            'actions::restore-action' => 'fas-rotate-left',
            'actions::restore-action.grouped' => 'fas-rotate-left',
            'actions::restore-action.modal' => 'fas-rotate-left',
            'actions::view-action' => 'fas-eye',
            'actions::view-action.grouped' => 'fas-eye',

            'forms::components.builder.actions.clone' => 'fas-clone',
            'forms::components.builder.actions.collapse' => 'fas-chevron-up',
            'forms::components.builder.actions.delete' => 'fas-trash',
            'forms::components.builder.actions.edit' => 'fas-pen-to-square',
            'forms::components.builder.actions.expand' => 'fas-chevron-down',
            'forms::components.builder.actions.move-down' => 'fas-arrow-down',
            'forms::components.builder.actions.move-up' => 'fas-arrow-up',
            'forms::components.builder.actions.reorder' => 'fas-up-down',
            'forms::components.checkbox-list.search-field' => 'fas-magnifying-glass',
            'forms::components.file-upload.editor.actions.drag-crop' => 'fas-crop',
            'forms::components.file-upload.editor.actions.drag-move' => 'fas-arrows-up-down-left-right',
            'forms::components.file-upload.editor.actions.flip-horizontal' => 'fas-left-right',
            'forms::components.file-upload.editor.actions.flip-vertical' => 'fas-up-down',
            'forms::components.file-upload.editor.actions.move-down' => 'fas-arrow-down',
            'forms::components.file-upload.editor.actions.move-left' => 'fas-arrow-left',
            'forms::components.file-upload.editor.actions.move-right' => 'fas-arrow-right',
            'forms::components.file-upload.editor.actions.move-up' => 'fas-arrow-up',
            'forms::components.file-upload.editor.actions.rotate-left' => 'fas-rotate-left',
            'forms::components.file-upload.editor.actions.rotate-right' => 'fas-rotate-right',
            'forms::components.file-upload.editor.actions.zoom-100' => 'fas-magnifying-glass',
            'forms::components.file-upload.editor.actions.zoom-in' => 'fas-magnifying-glass-plus',
            'forms::components.file-upload.editor.actions.zoom-out' => 'fas-magnifying-glass-minus',
            'forms::components.key-value.actions.delete' => 'fas-trash',
            'forms::components.key-value.actions.reorder' => 'fas-up-down',
            'forms::components.modal-table-select.actions.select' => 'fas-check',
            'forms::components.repeater.actions.clone' => 'fas-clone',
            'forms::components.repeater.actions.collapse' => 'fas-chevron-up',
            'forms::components.repeater.actions.delete' => 'fas-trash',
            'forms::components.repeater.actions.expand' => 'fas-chevron-down',
            'forms::components.repeater.actions.move-down' => 'fas-arrow-down',
            'forms::components.repeater.actions.move-up' => 'fas-arrow-up',
            'forms::components.repeater.actions.reorder' => 'fas-up-down',
            'forms::components.rich-editor.panels.custom-blocks.close-button' => 'fas-xmark',
            'forms::components.rich-editor.panels.custom-block.delete-button' => 'fas-trash',
            'forms::components.rich-editor.panels.custom-block.edit-button' => 'fas-pen-to-square',
            'forms::components.rich-editor.panels.merge-tags.close-button' => 'fas-xmark',
            'forms::components.select.actions.create-option' => 'fas-circle-plus',
            'forms::components.select.actions.edit-option' => 'fas-pen-to-square',
            'forms::components.text-input.actions.copy' => 'fas-copy',
            'forms::components.text-input.actions.hide-password' => 'fas-eye-slash',
            'forms::components.text-input.actions.show-password' => 'fas-eye',
            'forms::components.toggle-buttons.boolean.false' => 'fas-xmark',
            'forms::components.toggle-buttons.boolean.true' => 'fas-check',

            'infolists::components.icon-entry.false' => 'fas-xmark',
            'infolists::components.icon-entry.true' => 'fas-check',

            'notifications::database.modal.empty-state' => 'fas-bell-slash',
            'notifications::notification.close-button' => 'fas-xmark',
            'notifications::notification.danger' => 'fas-circle-exclamation',
            'notifications::notification.info' => 'fas-circle-info',
            'notifications::notification.success' => 'fas-circle-check',
            'notifications::notification.warning' => 'fas-triangle-exclamation',

            'panels::auth.multi-factor.app.actions.disable' => 'fas-shield-halved',
            'panels::auth.multi-factor.app.actions.disable.modal' => 'fas-shield-halved',
            'panels::auth.multi-factor.app.actions.disable.notification' => 'fas-shield-halved',
            'panels::auth.multi-factor.app.actions.regenerate-recovery-codes' => 'fas-rotate',
            'panels::auth.multi-factor.app.actions.regenerate-recovery-codes.modal' => 'fas-rotate',
            'panels::auth.multi-factor.app.actions.regenerate-recovery-codes.notification' => 'fas-rotate',
            'panels::auth.multi-factor.app.actions.set-up' => 'fas-shield',
            'panels::auth.multi-factor.app.actions.set-up.modal' => 'fas-shield',
            'panels::auth.multi-factor.app.actions.set-up.notification' => 'fas-shield',
            'panels::auth.multi-factor.email.actions.disable' => 'fas-envelope-circle-check',
            'panels::auth.multi-factor.email.actions.disable.modal' => 'fas-envelope-circle-check',
            'panels::auth.multi-factor.email.actions.disable.notification' => 'fas-envelope-circle-check',
            'panels::auth.multi-factor.email.actions.set-up' => 'fas-envelope',
            'panels::auth.multi-factor.email.actions.set-up.modal' => 'fas-envelope',
            'panels::auth.multi-factor.email.actions.set-up.notification' => 'fas-envelope',
            'panels::global-search.field' => 'fas-magnifying-glass',
            'panels::pages.dashboard.actions.filter' => 'fas-filter',
            'panels::pages.dashboard.navigation-item' => 'fas-house',
            'panels::pages.password-reset.request-password-reset.actions.login' => 'fas-arrow-left',
            'panels::pages.password-reset.request-password-reset.actions.login.rtl' => 'fas-arrow-right',
            'panels::resources.pages.edit-record.navigation-item' => 'fas-pen-to-square',
            'panels::resources.pages.manage-related-records.navigation-item' => 'fas-table-list',
            'panels::resources.pages.view-record.navigation-item' => 'fas-eye',
            'panels::sidebar.collapse-button' => 'fas-angles-left',
            'panels::sidebar.collapse-button.rtl' => 'fas-angles-right',
            'panels::sidebar.expand-button' => 'fas-angles-right',
            'panels::sidebar.expand-button.rtl' => 'fas-angles-left',
            'panels::sidebar.group.collapse-button' => 'fas-chevron-up',
            'panels::sub-navigation.mobile-menu.button' => 'fas-chevron-down',
            'panels::tenant-menu.billing-button' => 'fas-credit-card',
            'panels::tenant-menu.profile-button' => 'fas-gear',
            'panels::tenant-menu.registration-button' => 'fas-plus',
            'panels::tenant-menu.toggle-button' => 'fas-chevron-down',
            'panels::theme-switcher.light-button' => 'fas-sun',
            'panels::theme-switcher.dark-button' => 'fas-moon',
            'panels::theme-switcher.system-button' => 'fas-desktop',
            'panels::topbar.close-sidebar-button' => 'fas-xmark',
            'panels::topbar.open-sidebar-button' => 'fas-bars',
            'panels::topbar.group.toggle-button' => 'fas-chevron-down',
            'panels::topbar.open-database-notifications-button' => 'fas-bell',
            'panels::sidebar.open-database-notifications-button' => 'fas-bell',
            'panels::user-menu.profile-item' => 'fas-circle-user',
            'panels::user-menu.logout-button' => 'fas-arrow-right-from-bracket',
            'panels::user-menu.toggle-button' => 'fas-chevron-up',
            'panels::widgets.account.logout-button' => 'fas-arrow-right-from-bracket',
            'panels::widgets.filament-info.open-documentation-button' => 'fas-book-open',
            'panels::widgets.filament-info.open-github-button' => 'fas-code-branch',

            'query-builder::add-rule-action' => 'fas-plus',
            'query-builder::constraints.boolean' => 'fas-toggle-on',
            'query-builder::constraints.date' => 'fas-calendar-days',
            'query-builder::constraints.number' => 'fas-hashtag',
            'query-builder::constraints.relationship' => 'fas-arrows-left-right',
            'query-builder::constraints.select' => 'fas-list',
            'query-builder::constraints.text' => 'fas-font',
            'query-builder::or-group.block' => 'fas-slash',
            'query-builder::or-group.add-group-action' => 'fas-plus',

            'schema::components.callout.danger' => 'fas-circle-xmark',
            'schema::components.callout.info' => 'fas-circle-info',
            'schema::components.callout.success' => 'fas-circle-check',
            'schema::components.callout.warning' => 'fas-triangle-exclamation',
            'schema::components.tabs.dropdown-trigger-button' => 'fas-ellipsis',
            'schema::components.tabs.more-tabs-button' => 'fas-ellipsis',
            'schema::components.wizard.completed-step' => 'fas-check',

            'badge.delete-button' => 'fas-xmark',
            'breadcrumbs.separator' => 'fas-chevron-right',
            'breadcrumbs.separator.rtl' => 'fas-chevron-left',
            'modal.close-button' => 'fas-xmark',
            'pagination.first-button' => 'fas-angles-left',
            'pagination.first-button.rtl' => 'fas-angles-right',
            'pagination.last-button' => 'fas-angles-right',
            'pagination.last-button.rtl' => 'fas-angles-left',
            'pagination.next-button' => 'fas-chevron-right',
            'pagination.next-button.rtl' => 'fas-chevron-left',
            'pagination.previous-button' => 'fas-chevron-left',
            'pagination.previous-button.rtl' => 'fas-chevron-right',
            'section.collapse-button' => 'fas-chevron-up',

            'tables::actions.disable-reordering' => 'fas-lock',
            'tables::actions.enable-reordering' => 'fas-lock-open',
            'tables::actions.filter' => 'fas-filter',
            'tables::actions.group' => 'fas-layer-group',
            'tables::actions.open-bulk-actions' => 'fas-list-check',
            'tables::actions.column-manager' => 'fas-table-columns',
            'tables::columns.collapse-button' => 'fas-chevron-down',
            'tables::columns.icon-column.false' => 'fas-xmark',
            'tables::columns.icon-column.true' => 'fas-check',
            'tables::empty-state' => 'fas-inbox',
            'tables::filters.remove-all-button' => 'fas-xmark',
            'tables::grouping.collapse-button' => 'fas-chevron-up',
            'tables::header-cell.sort-asc-button' => 'fas-arrow-up-short-wide',
            'tables::header-cell.sort-button' => 'fas-sort',
            'tables::header-cell.sort-desc-button' => 'fas-arrow-down-wide-short',
            'tables::reorder.handle' => 'fas-grip',
            'tables::search-field' => 'fas-magnifying-glass',

            'widgets::chart-widget.filter' => 'fas-filter',
            'widgets::chart-widget.empty-state' => 'fas-chart-line',
        ]);
    }
}
